server:
    port: 8080

logging:
    level:
        org.springframework.context: info

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate

application:
    security:
        jwt:
            secret-key: '5468576D5A7133743677397A24432646294A404E635266556A586E3272357537'
