server:
  port: 8081

logging:
  level:
    org.springframework.context: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/certificates-secure
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
